### ISSUE TITLE
How to derive wavelength data

### ISSUE THREAD

**Issue by bicarlsen** [fujiisoup/sif_reader#14]
Thank you for creating this package. I'm having trouble deriving the wavelength data from the information given using the `np_open` function. Can you describe how to go about this?

My attempt so far has been
```python
import sif_reader as sif

data, info = sif.np_open('0.sif')
cal = info['Calibration_data']
# it appeared as thoutgh cal[0] was the wavelength for pixel 1 and cal[1] was the wavelength difference between pixels,
# however this doews not appear to be the case.

# this gives the incorrect wavelength when compared to the exported data.
last_pixel = cal[0] + cal[1] * info['size'][0]
```

**Comment by fujiisoup** [comment]
Hi. Thank you for raising this issue.

Could to post a data to this thread? I don't use calibration data usually
and have no data to test with.

To upload the file, see this link
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Comment by fujiisoup** [comment]
Looks like `info['Calibration_data']` is a polynomial coefficient.
Could you try the following?
https://github.com/fujiisoup/sif_reader/blob/916cf48a6f281a2729f82c8d253cbeb942a94cdc/sif_reader/utils.py#L33-L34

**Comment by bicarlsen** [comment]
The above was the solution. Thank you. I had actually tried using the calibration coefficients as polynomial coefficients but had an error in my code which was giving the incorrect result, so got lost on how to use them.

Can I suggest putting something about the `utils` in the README as it is quite a useful tool.

**Comment by fujiisoup** [comment]
Sounds great! Contribution is very welcome.
