### ISSUE TITLE
Add to PyPI

### ISSUE THREAD

**Issue by bicarlsen** [fujiisoup/sif_reader#15]
It would be great to have this package on PyPI. I'm using it to build a CLI and it would be nice to have it as an external dependency instead of having to copy the code directly.

**Comment by fujiisoup** [comment]
Thanks for the suggestion. V I'll work with it, but it may take a while to remember how to upload pypi.

**Comment by bicarlsen** [comment]
Here is the package using yours, if you're interested: https://github.com/bicarlsen/andor_sif

**Comment by bicarlsen** [comment]
We can certainly do that. I'll create a PR in the next weeks. I can also include the PyPI info for upload.

**Comment by rjlopez2** [comment]
You guys are awesome :)
thanks a lot for this effort.
will hear from me soon, since I will probably rely heavily on your nice job.
Again thanks

**Comment by bicarlsen** [comment]
@fujiisoup I'd be happy to upload the package to PyPI under my account if you wish, as well. Let me know what you wish to do.

**Comment by fujiisoup** [comment]
@bicarlsen 
> I'd be happy to upload the package to PyPI under my account if you wish, as well.
It sounds reasonable to me!

**Comment by bicarlsen** [comment]
There is another project called [`sifread`](https://pypi.org/project/sifreader/) (no hyphen) that is too similar to `sif-reader` for us to upload to PyPI using that name. On the [GitHub for the project](https://github.com/lightingghost/sifreader) it is stated that the project is no longer maintained. I've raised an [issue bringing this project to their awarenss](https://github.com/lightingghost/sifreader/issues/11) but have not yet heard back.

I see two ways of moving forward:
1. Changing the name of the project. Perhaps using the [`andor-sif`](https://pypi.org/project/andor-sif/) project I originally created.
2. Contacting the authors of the `sifreader` project directly to see if they respond and if they think it's a good idea and are willing to merge the two projects.

Please let me know your opinion on what you think the best path forward is.

**Comment by bicarlsen** [comment]
Maybe `sif_parser`?

**Comment by bicarlsen** [comment]
To facilitate this we have moved the package to a new name ([fujiisoup/sif_parser](https://github.com/fujiisoup/sif_parser/)) and added it to the Test PyPI repository for review. Please make any comments in [Issue #3 of `sif_parser`](https://github.com/fujiisoup/sif_parser/issues/3)

[TestPyPI/sif_parser](https://test.pypi.org/project/sif-parser/0.3.0/)

**Comment by bicarlsen** [comment]
The package has been added to PyPI: https://pypi.org/project/sif-parser

**Comment by fujiisoup** [comment]
Great! Thank you!
