### ISSUE TITLE
Problem to read .sif image

### ISSUE THREAD

**Issue by rjlopez2** [fujiisoup/sif_reader#21]
I am having issues to read some images I have recently acquired with a A-Zyla-5.5-CL10.
Your script work fine with a series of old images I acquired in a different setup with similar camera. However, since we recently built our setup and test your script to try to open new images, I am facing some issues to open the file.

This is the retrieved metadata when using the function sif_reader calling the image that works:
`data1, info1 = sif_reader.np_open(my_sample_img)`
and this is the oupuoutputot of `"info1"`

`
OrderedDict([('SifVersion', 65567),
             ('ExperimentTime', 1637915564),
             ('DetectorTemperature', 0.0),
             ('ExposureTime', 0.0047),
             ('CycleTime', 0.00480163),
             ('AccumulatedCycleTime', 0.00480163),
             ('AccumulatedCycles', 1),
             ('StackCycleTime', 0.00480163),
             ('PixelReadoutTime', 1.78571e-09),
             ('GainDAC', 2.0),
             ('DetectorType', 'ZYLA-5.5-CL10 \n'),
             ('DetectorDimensions', (1950, 370)),
             ('OriginalFilename',
              b'C:\\Users\\PanoramicMapping\\Documents\\Optical Mapping\\Recordings/2021.11.26/10h-32m-47s.sif'),
             ('ShutterTime', (0.0, 0.0)),
             ('spectrograph', 'Spectrograph_None999'),
             ('SifCalbVersion', 65540),
             ('Calibration_data', [0.0, 1.0, 0.0, 0.0]),
             ('FrameAxis', b'Pixel number'),
             ('DataType', b'Counts'),
             ('ImageAxis', b'Pixel number'),
             ('NumberOfFrames', 500),
             ('NumberOfSubImages', 1),
             ('TotalLength', 360750000),
             ('ImageLength', 721500),
             ('xbin', 1),
             ('ybin', 1),
             ('timestamp_of_0', 0),
             ('timestamp_of_1', 4804),
             ('timestamp_of_2', 9609),
             ('timestamp_of_3', 14413),
             ('timestamp_of_4', 19218),
             ('timestamp_of_5', 24022),
             ('timestamp_of_6', 28827),
             ('timestamp_of_7', 33631),
             ('timestamp_of_8', 38436),
             ('timestamp_of_9', 43240),
             ('timestamp_of_10', 48045),
             ('timestamp_of_11', 52849),
             ('timestamp_of_12', 57654),
             ('timestamp_of_13', 62458),
             ('timestamp_of_14', 67263),
             ('timestamp_of_15', 72067),
             ('timestamp_of_16', 76872),
             ('timestamp_of_17', 81676),
             ('timestamp_of_18', 86481),
             ('timestamp_of_19', 91285),
             ('timestamp_of_20', 96090),
             ('timestamp_of_21', 100894),
             ('timestamp_of_22', 105699),
             ('timestamp_of_23', 110503), ...)]
`

While reading the new images in our new set-up I receive the following error:

`ValueError                                Traceback (most recent call last)
<ipython-input-10-dc2e53d70974> in <module>
----> 1 dat2, info2 = sif_reader.np_open(my_sample_img2)

~/.pyenv/versions/3.8.8/lib/python3.8/site-packages/sif_reader-0.2.0-py3.8.egg/sif_reader/sif_open.py in np_open(sif_file)
     18     for i, tile1 in enumerate(tile):
     19         f.seek(tile1[2])  # offset
---> 20         data[i] = np.fromfile(f, count=size[0]*size[1],dtype='<f').reshape(size[1],size[0])
     21 
     22     try:

ValueError: cannot reshape array of size 300235 into shape (450,1530)`

Attached see the screenshot of the Andor-Solis version I used to acquire the data.
I am not so literate in python nor Matlab, but I can provide further information / files examples if you need it.

Appreciate your support

Best

![ANDOR_Solis_version](https://user-images.githubusercontent.com/33715817/176901998-a5d1775f-707b-48e4-bff1-661854b26576.jpg)

**Comment by fujiisoup** [comment]
Hi, @rjlopez2 
Thank you for raising an issue.

This may happen, as I have not tested `sif_reader` for the data by a zyla camera.

Do you mind to share your data? Without the data, it is difficult to debug.
It would be appreciated if you could upload the data here (see https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files for uploading the data).

Please note that we will put your data in a public space for the testing purpose. Don't upload confidential data.

**Comment by fujiisoup** [comment]
Thank you! @rjlopez2 

Could you also share the file by Zyla camera that sif_reader is able to read?
(It would be great if you could have smaller file for both the cases. Github has some storage limitation...)

**Comment by fujiisoup** [comment]
@rjlopez2 Are you able to read this file by Andor SOLIS?

The file size is ~84 MB. The image size is 1530x450 pixels, which corresponds to 2.75 MB for each frame.
It gives me a rough estimate, where the file contains ~30 frames.

However, the header says (as far as I can tell from my script), it should contain 2000 frames. 
`sif_reader` try to read the 31st frame from the file, but there are as there no more frames it crashes.

Do you know how many frames it has in the file?

**Comment by rjlopez2** [comment]
@fujiisoup
To your first question:
in our new setup I can generate any size images. I will try to upload smaller ones for your testing purpose. For the image(s) that can be read using `sif_reader` I only have access to few of them and they are very heavy (>1GB). I will try to find one for you that is smaller, otherwise will have to share it using a different method :/
To your second question:
In deed, that image should contain 2000 frames. However it may be corrupted since when saving it it throwed an error. Nevertheless, I could open it with Andor Solis software withought problem and showed the 2000 frames.
Again, I can try to collect new smaller images but will not be before Tuesday when I am back in the lab :/

**Comment by rjlopez2** [comment]
You can download [this](https://wormhole.app/OOQYW#h2QetmJFdJErZr8AtQdC_Q) image just for playing but be aware is about 1.2 GB
This one can be opened using the `sif_reader`
This link expire in 24 h, but I could re-upload if you need more time.

**Comment by fujiisoup** [comment]
Thank you, @rjlopez2 

> In deed, that image should contain 2000 frames. However it may be corrupted since when saving it it throwed an error. 

OK. Then, it looks like the problem is here. Now, `sif_reader` assumes that all the images are stored in the file.
Maybe we can change its behavior.

One option would be to read as many as possible, and if the total number of the images read are smaller than that written in the header, we may raise a warning.
This should be easy to be implemented.

Do you have any recommended behavior for such a case?

**Comment by rjlopez2** [comment]
> One option would be to read as many as possible, and if the total number of the images read are smaller than that written in the header, we may raise a warning.
it sounds as a good solution for me :)

**Comment by fujiisoup** [comment]
Hi @rjlopez2 

Now, corrupt file is supported.
You can read the corrupt file by `sif_parser.np_read(filename, ignore_corrupt=True)`.

By the way, we decided to rename this package to `sif_parser`. 
Please move to [sif_parser](https://github.com/fujiisoup/sif_parser) at your convenience!

**Comment by rjlopez2** [comment]
HI again @fujiisoup 

installing the renamed package via 

`pip install sif_parser`

or via

`pip install git+https://www.github.com/fujiisoup/sif_parser`

Installation as indicated in your new [repo](https://github.com/fujiisoup/sif_parser#install) does not seems to reveal the new changes.

I uninstall and reinstall the package and tried with fresh conda env en still not working.
It says, for instance that the new argument  `ignore_corrupt` cannot be found.
`TypeError: np_open() got an unexpected keyword argument 'ignore_corrupt'`

Could you please check this estrange behavior for me?

thanks again

**Comment by fujiisoup** [comment]
Oops. I forgot to update the version info of the package.
Although the one in PYPI is not updated,
`pip install git+https://www.github.com/fujiisoup/sif_parser`
should install the new version.

I'm sorry for the inconvenience

**Comment by rjlopez2** [comment]
Hey Thanks
I could finally see my barrels using your script (if you know what I mean ;)

Just a last comment, when `ignore_corrupt = False` the message says that the number of images found and listed are the same?

Here is the message:

`ValueError: The file might be corrupt. Number of files should be 2000 according to the header, but only 2000 is found in the file.Use "ignore_corrupt=True" keyword argument to ignore.`

In any case, the expected image (or corrupted frames) are displayed  when `ignore_corrupt = True`

Again thanks lot for your support!

**Comment by fujiisoup** [comment]
Thanks for the comments. It is defenitely wrong... Wait for a moment.
